### ISSUE TITLE
Determine whether device supports SMS without opening message

### ISSUE THREAD

**Issue by aarongreenwald** [anarchicknight/react-native-message-composer#1]
This is more of a feature request than a bug, and if it's something you'd accept I can try to work on a PR for this:

It would be nice if there was a method that would check if device supports SMS but doesn't actually open a new message if the device does support it. A common use case is to check if the device will allow SMS and hide/show certain features based on the result. Currently it seems the only way to do this is to try to open a new message and handle the failure.

**Comment by anarchicknight** [comment]
I use the [MFMessageComposeViewController canSendText] method within the composeMessageWithArgs method currently to determine whether we should open the message controller.

It should be trivial to split this out in to its own method call which can be accessed via JS on the react-native side.

I can probably get to look at this on the weekend, but if you want to go ahead with a PR for it instead before then that is fine with me too.

**Comment by aarongreenwald** [comment]
Ok great, I'll give it a shot if I have some time.

**Comment by anarchicknight** [comment]
resolved via #2
