### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by apastel** [anarchicknight/react-native-message-composer#3]
Any plans for Android implementation, or recommendations of other modules?

**Comment by Prims47** [comment]
:+1:

**Comment by anarchicknight** [comment]
Android does not have any control which will open a message compose window within your own app - if you want a view to keep you in your own app you will need to design & code it manually.

The other option is to use the android intent system - this will allow the user to launch any app which supports sending sms messages, but this is launched outside of your own app. If you use the startActivityForResult method it will return you to your app.

If I get the time I will take a look and see how feasible it is to add that support to this module.

In the meantime, maybe the following module will help? https://github.com/lucasferreira/react-native-send-intent

**Comment by mehcode** [comment]
React Native has built-in support for intents with `Linking`. See https://github.com/anarchicknight/react-native-communications for an easy-to-use wrapper that supports this.

**Comment by anarchicknight** [comment]
This module was made for a specific reason of opening a message view within your own app.

This is not possible on Android as discussed above. 

There are other modules already discussed which have support for launching a message view outside of your app.

Going to close this

**Comment by nihp** [comment]
Can any one suggest any package for this support. Need to work for both iOS and android.
