### ISSUE TITLE
Enhancement: Use rnpm to setup project/configure Xcode

### ISSUE THREAD

**Issue by dwilt** [anarchicknight/react-native-message-composer#4]
First off, thank you for building this plugin. This is exactly what I was looking for when I realized [react-native-communications](https://github.com/anarchicknight/react-native-communications) couldn't prefill the text message. Was going through your setup, and although your directions are very well explained, I am a bit stuck on the last one:

>  Look for Header Search Paths and make sure it contains both $(SRCROOT)/../react-native/React and $(SRCROOT)/../../React - mark both as recursive.

Since I have no idea about what's going on in Xcode, I'm not sure if what I have is correct - it doesn't look correct:
<img width="749" alt="screenshot 2016-07-14 00 44 58" src="https://cloud.githubusercontent.com/assets/1065539/16831881/511ad22a-495c-11e6-889f-a4d3dfced19b.png">
So then I figured, I might as well make an issue requesting that all this be setup by rnpm :)

**Comment by dwilt** [comment]
For anyone who else was stuck as I was, literally copied and pasted both `$(SRCROOT)/../react-native/React` and `$(SRCROOT)/../../React` into the window that came up in Xcode when you double clicked on value column of the `Header Search Paths` and set both to recursive. I ended up with the following:

![screenshot 2016-07-14 11 22 27](https://cloud.githubusercontent.com/assets/1065539/16850710/426f0102-49b5-11e6-8f73-1e40d79b07f3.png)

I'm leaving this issue open because it would be best to just have it automatically `link`ed via rnpm

**Comment by anarchicknight** [comment]
Hey,

Thanks for the report.

rpm should already be supported. Just tested it on a sample project and it was fine.

npm install --save react-native-message-composer
then rpm link

I will get the README updated with these instructions - won't close the issue until the README is updated

**Comment by anarchicknight** [comment]
updated instructions and published new patch version
