### ISSUE TITLE
It is better if we set animation as false when the popview dismiss.

### ISSUE THREAD

**Issue by jiangsumadai** [anarchicknight/react-native-message-composer#7]
-(void)messageComposeViewController:(MFMessageComposeViewController *)controller didFinishWithResult:(MessageComposeResult)result {
...
[vc dismissViewControllerAnimated:TRUE completion:nil];
...
}

**Comment by jiangsumadai** [comment]
否则有卡顿

**Comment by anarchicknight** [comment]
Can you explain the benefits that are introduced by setting animation to false?

I may look at providing it as an option for user to choose either true or false but before I do some info on the above would be useful

**Comment by anarchicknight** [comment]
added optional args to animate presentation & dismissal of view controller in version 0.1.0
